language: c

os:
  - osx
  - linux

sudo: required

addons:
  apt:
    packages:
      - byacc
      - flex
      - pkg-config
      - libpng-dev

before_install: ./script/bootstrap

script: make check
